name: CI/CD MLflow - Stunting Detection

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  EXPERIMENT_NAME: Stunting_Detection_XGBoost_Model_Tuning
  MLFLOW_TRACKING_URI: https://dagshub.com/nandaarya/stunting-detection.mlflow
  MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
  MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install Python Dependencies (from conda.yaml)
      run: |
        pip install --upgrade pip
        pip install mlflow==2.22.0 \
                    mlflow_skinny==2.22.0 \
                    numpy==2.2.6 \
                    optuna==4.3.0 \
                    pandas==2.3.0 \
                    scikit_learn==1.7.0 \
                    xgboost==3.0.2

    - name: Run MLflow Project
      run: |
        mlflow run . --env-manager=local --run-name stunting_xgb_run

    - name: Get latest MLflow run_id
      run: |
        echo "Fetching latest run ID from experiment..."
        python <<EOF
        import mlflow
        client = mlflow.tracking.MlflowClient()
        experiment = client.get_experiment_by_name("${{ env.EXPERIMENT_NAME }}")
        if not experiment:
            raise Exception("Experiment not found.")
        runs = client.search_runs(experiment_ids=[experiment.experiment_id], order_by=["start_time DESC"])
        run_id = runs[0].info.run_id
        print("Latest run ID:", run_id)
        with open("${GITHUB_ENV}", "a") as f:
            f.write(f"RUN_ID={run_id}\n")
        EOF

    - name: Download Model Artifact
      run: |
        mlflow artifacts download \
          --run-id $RUN_ID \
          --artifact-path xgboost_model \
          --dst-path downloaded_model

    - name: Upload Model Artifact to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: xgboost_stunting_model
        path: downloaded_model/

    - name: Build Docker Image from MLflow Model
      run: |
        mlflow models build-docker \
          --model-uri "runs:/$RUN_ID/xgboost_model" \
          --name "stunting_xgb_image"

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag Docker Image
      run: |
        docker tag stunting_xgb_image ${{ secrets.DOCKER_USERNAME }}/stunting-xgb-model:latest

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/stunting-xgb-model:latest